### ISSUE TITLE
multimethod.multimethod w/ arity of 1

### ISSUE THREAD

**Issue by peteut** [coady/multimethod#1]
Regarding `multimethod.multimethod` w/ arity of 1 consider this:

```python
from multimethod import multimethod

def clone_of_default(x):
    raise NotImplementedError("no implementation for {} found".format(type(x))) 

clone_of = multimethod(clone_of_default)
clone_of[(int,)] = lambda x: int(x)
```

Adding a method like, which I tried first:

```python
clone_of[int] = lambda x: int(x)
```

yields `TypeError: 'type' object is not iterable`.

What is the desired behaviour for arity 1?

**Comment by peteut** [comment]
Ok, my bad. It's according the spec.

**Comment by coady** [comment]
The parens can be omitted too.
```python
clone_of[int,]
```
