### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by albop** [coady/multimethod#10]
Thanks @coady for this package. It has been quite useful to me! Have you ever releasing it on conda-forge so that other packages can depend on it?

Also, I've been trying to decide which package to use between this one and multipledispatch (https://github.com/mrocklin/multipledispatch). I gather that the latter does not supprt keyword arguments which multimethod seems to understand. Appart from that is there a reason to choose one or another?

**Comment by coady** [comment]
> Thanks @coady for this package. It has been quite useful to me! Have you ever releasing it on conda-forge so that other packages can depend on it?

I haven't, but I'm not opposed to it.  Would you be interested in maintaining the conda recipe?

> Also, I've been trying to decide which package to use between this one and multipledispatch (https://github.com/mrocklin/multipledispatch). I gather that the latter does not supprt keyword arguments which multimethod seems to understand. Appart from that is there a reason to choose one or another?

It looks similar, in features and performance.  Features that are unique to multimethod (AFAIK):
* support for type hints
* support for forward references
* `overload` supports predicate dispatch

**Comment by albop** [comment]
Yes, I spent some of the week creating several packages for my own stuff, so I can certainly create (and maintain) one for your package.

**Comment by albop** [comment]
Thanks, for the details. I think multipledispatch actually supports type hints (don't know why it's not in their docs).

**Comment by albop** [comment]
Done. The package has been released on conda-forge. You can install with `conda install -c conda-forge multimethod`. @coady, I should get an automatic notification when you make a new release on PyPi but don't hesitate me to ping me just in case.

**Comment by coady** [comment]
Thanks!
