### ISSUE TITLE
Clarify if `@multimethod` works with position-or-keyword arguments

### ISSUE THREAD

**Issue by ParadaCarleton** [coady/multimethod#101]
Right now `@multimethod` dispatch is documented as "positional only"--does that mean it only dispatches on arguments that are positional-only, or does it dispatch on arguments that are positional-or-keyword?

**Comment by coady** [comment]
`multimethod` only dispatches on positional _arguments_ (from the caller). Which means positional-only or positional-or-keyword _parameters_ (the function definition).

`multidispatch` includes support for keyword arguments.
