### ISSUE TITLE
[Feature Request(Maybe)] Support for Ellipsis

### ISSUE THREAD

**Issue by hzhangxyz** [coady/multimethod#17]
Currently multimethod cannot recognize type contaning ellipsis such as `tuple[int, ...]`
However it is a standard way to declare variable-length tuple
ref: https://docs.python.org/3/library/typing.html#typing.Tuple

Maybe add another check in [`__init__.py:subtype.__subclasscheck__`](https://github.com/coady/multimethod/blob/main/multimethod/__init__.py#L66) would help

**Comment by hzhangxyz** [comment]
It seems change `__init__.py:subtype.__subclasscheck__` to this works, but it is really an ugly solution
```
    def __subclasscheck__(self, subclass):
        origin = getattr(subclass, '__extra__', getattr(subclass, '__origin__', subclass))
        args = getattr(subclass, '__args__', ())
        if origin is typing.Union:
            return all(issubclass(cls, self) for cls in args)
        if self.__origin__ is typing.Union:
            return issubclass(subclass, self.__args__)
        issubclass_fixed = lambda x,y : x == y == Ellipsis or issubclass(x,y)
        return (  # check args first to avoid a recursion error in ABCMeta
            len(args) == len(self.__args__)
            and issubclass(origin, self.__origin__)
            and all(map(issubclass_fixed, args, self.__args__))
        )
```

**Comment by hzhangxyz** [comment]
The above change cannot solve ellipsis, see
```

**Comment by hzhangxyz** [comment]
Maybe it is correct way to update something in class `subclass`? I don't know about it

**Comment by coady** [comment]
For this use case, it would be simpler (and faster) to use `Iterable` or `Sequence`.  But I guess it might as well be supported, to not look like a bug.  Thanks.

**Comment by hzhangxyz** [comment]
In my case, I want `tuple[tuple[int, int], ...]` to be the key of dict, so it seems `Iterable` or `Sequence` not work.

Thanks for solving this.
