### ISSUE TITLE
Time for new release?

### ISSUE THREAD

**Issue by adam-urbanczyk** [coady/multimethod#50]
I'd like use the latest developments in a project (especially the partial literal support). Are there any plans to release 1.6?

**Comment by coady** [comment]
I was waiting for Python 3.10 to be released, but I guess release candidate is close enough. I'll publish a new release this weekend.

**Comment by adam-urbanczyk** [comment]
Thanks!

**Comment by coady** [comment]
Released [v1.6](https://github.com/coady/multimethod/releases/tag/v1.6).
