### ISSUE TITLE
Add interface like singledispatchmethod

### ISSUE THREAD

**Issue by ZeeD26** [coady/multimethod#6]
Python 3.8 saw the introduction of [functools.singledispatchmethod](https://docs.python.org/3/library/functools.html#functools.singledispatchmethod). I would love to see support for the same interface in a multipledispatchmethod.

**Comment by coady** [comment]
Methods are already supported:
```python
class Negator: 
    @multimethod 
    def neg(self, arg: int): 
        return -arg 

    @neg.register 
    def _(self, arg: bool): 
        return not arg                                                                                                                                                                                                                                         

In []: Negator().neg(1)                                                                                                                                                                                                                        
Out[]: -1

In []: Negator().neg(True)                                                                                                                                                                                                                     
Out[]: False
```
If an param on the left has no annotation, it's equivalent to having an `: object` annotation.

**Comment by ZeeD26** [comment]
Actually, I was thinking of support of the register method without type annotation. But I reckon it's possible using `object` as first type?

**Comment by coady** [comment]
Ah, yes: `.register(object, ...)` works.

I guess it's time to fully support and document `@register(*types)`.  This project pre-dates Python 3 and `singledispatch`, and it wasn't clear if annotations would be preferred.  But the original `singledispatch` style still seems popular, even with the end of Python 2.

**Comment by coady** [comment]
da2fdb3 documents this feature more clearly.  Thanks.
