### ISSUE TITLE
Doesn't work properly with pydantic types

### ISSUE THREAD

**Issue by akhundMurad** [coady/multimethod#78]
Hello! I am trying to use it with `pydantic.BaseModel` and I am facing the issue:
```python
class Mapper:
    @multimethod
    def map(self, source, target_type):
        ...

    @map.register
    def _(self, source: ProfileDTO, target_type: typing.Type[UserDTO]) -> UserDTO:
        # logic
        ...
```
Where `ProfileDTO` and `UserDTO` are pydantic models.

Then I am trying to use this class:
```python
mapper = Mapper()
mapper.map(profile, UserDTO)
```
But the library doesn't use the registered method, because it recognizes `typing.Type[UserDTO]` construction like `pydantic.main.ModelMetaclass`.

Is there some solution for this?

**Comment by coady** [comment]
It should work with pydantic classes, that is, anything which supports `issubclass`. The problem appears to be not supporting `Type[...]`. Some workarounds to try which are similar:
* `Literal[...]`: which won't match subclasses
* `type(...)`: which will match instances of its metaclass.

**Comment by akhundMurad** [comment]
Thanks for quick response!
