### ISSUE TITLE
Documentation isn't updated?

### ISSUE THREAD

**Issue by svaningelgem** [coady/multimethod#88]
I checked https://multimethod.readthedocs.io/en/latest/readme.html#changes, but the latest version there is 1.4.

Is this something that could be updated with the latest version? (maybe as part of the build process)

**Comment by coady** [comment]
The documentation is hosted on GitHub: https://coady.github.io/multimethod.

**Comment by svaningelgem** [comment]
I'm unsure why the link is there then? And why conda (not the smallest package manager) has the link set: https://anaconda.org/conda-forge/multimethod?

Maybe something to look into?

**Comment by coady** [comment]
The conda package was maintained by a contributor: #10, @albop. I don't know what the status is.

**Comment by albop** [comment]
I'm still getting notifications for each new version and validate a PR to update the conda package (not super fast though). I have just merged 1.9.1.
As for the link to the documentation I have updated it in the conda recipe (https://github.com/conda-forge/multimethod-feedstock/blob/main/recipe/meta.yaml) . It will be corrected in the next update.

**Comment by coady** [comment]
> As for the link to the documentation I have updated it in the conda recipe (https://github.com/conda-forge/multimethod-feedstock/blob/main/recipe/meta.yaml) . It will be corrected in the next update.

Thanks!
